version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "13:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=tarea
    networks:
      - red_app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: tarea
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  
    networks:
      - red_app

networks:
  red_app:
    driver: bridge

volumes:
  db_data:
